// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetActiveTasks() {
  return window['go']['main']['App']['GetActiveTasks']();
}

export function GetCompletedTasks() {
  return window['go']['main']['App']['GetCompletedTasks']();
}

export function GetExpiredTasks() {
  return window['go']['main']['App']['GetExpiredTasks']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetTasksByDate() {
  return window['go']['main']['App']['GetTasksByDate']();
}

export function GetTasksByPriority() {
  return window['go']['main']['App']['GetTasksByPriority']();
}

export function GetTasksDueToday() {
  return window['go']['main']['App']['GetTasksDueToday']();
}

export function GetTasksDueWeek() {
  return window['go']['main']['App']['GetTasksDueWeek']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
