// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function AddTask(arg1:repository.Task):Promise<number>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetActiveTasks():Promise<Array<repository.Task>>;

export function GetCompletedTasks():Promise<Array<repository.Task>>;

export function GetExpiredTasks():Promise<Array<repository.Task>>;

export function GetTasks():Promise<Array<repository.Task>>;

export function GetTasksByDate():Promise<Array<repository.Task>>;

export function GetTasksByPriority():Promise<Array<repository.Task>>;

export function GetTasksDueToday():Promise<Array<repository.Task>>;

export function GetTasksDueWeek():Promise<Array<repository.Task>>;

export function Greet(arg1:string):Promise<string>;

export function UpdateTask(arg1:repository.Task):Promise<void>;
